### ISSUE TITLE
Alumni stylesheet/template

### ISSUE THREAD

**Issue by heatherahans** [DukeLearningInnovation/duke-sakai-skins#30]
Here is the stylesheet we'd like to implement for Duke Alumni/Extend courses in Sakai. I've attached screenshots, and I'm using the stylesheet on the Sakai site called [Alumni Template](https://sakai.duke.edu/portal/site/alumni-template).

Please take my stylesheet with a grain of salt; I'm still learning, and also, I know that some properties, such as text sizes, are irrelevant because we're defaulting to the Bootstrap defaults.

And please let me know if you have any questions! Thank you :)

<img width="1318" alt="extend-alum-overview" src="https://user-images.githubusercontent.com/42656903/47230743-1163a480-d399-11e8-8fba-8fcf41129660.png">

![extend-alum-course-intro](https://user-images.githubusercontent.com/42656903/47230857-58ea3080-d399-11e8-9d88-5c1de63c62af.png)

![extend-alum-week1](https://user-images.githubusercontent.com/42656903/47230872-61db0200-d399-11e8-80e8-02df4e1ffa12.png)

```CSS
.column a[href] {
    color: #0736A4;
    text-decoration: none;
}

a[href]:hover {
	color: #003366;
	text-decoration:underline;
	font-weight:400;
}

body {
	color: #262626;
    font-family: 'Open Sans', sans-serif;
	font-style: normal;
	font-weight: 400;
    font-size: 16px;
	-webkit-font-smoothing: antialiased;
}

/* Header Text Styles */

h1 {
	font-size: 33px;
	font-style: normal;
	font-weight: 400;
	color: #235F9C;
	line-height: 40px;
	font-family: 'Roboto Slab', Palatino;
	margin: 0 0 15px 0;
}

h2 {
	font-size: 28px;
	color: #666666;
	font-weight: 400;
	font-family: 'Open Sans', sans-serif;
	margin: 0 0 15px 0;
	line-height: 32px;
}

h3 {
    font-family: 'Open Sans', sans-serif;
	color: #262626;
    font-weight: 300;
	font-size: 22px;
	line-height: 25px;
}

h4 {
	font-size: 22px;
	font-weight: 600;
	color: #d75404;
	font-family: 'Roboto Slab', Palatino;
}

h5 {
	font-size: 14px;
	font-weight: 600;
	color: #6e6f71;
	font-family: 'Open Sans', sans-serif;
	text-transform: uppercase;
	line-height: 18px;
}

p {
	font-family: 'Open Sans', sans-serif;
	font-weight: 400;
	font-size: 16px;
	color: #262626;
	line-height: 28px;
}


li {
	font-family: 'Open Sans', sans-serif;
	font-size: 15px;
}

ul {
	list-style-type: disc;
	padding-bottom: 6px;
	font-weight: inherit;
	overflow: hidden;
}

blockquote {
	font-family:'Open Sans', sans-serif; 
	font-size:15px;
	color: #262626;
    font-weight: 400;
	margin: 20px 0;
	padding: 10px; 
	border-left: 5px solid #003366;
	background: #E4EDFA;
	padding-left: 1.5rem;
} 

blockquote:before {
    color: #003366;
}

blockquote:after {
    color: #003366;
}

hr {
	height: 2px;
	width: 100%;
	border-style: dotted;
	border-width: 2px 0 0 0;
	border-color: #6e6f71;
}

/* Float images left or right with margin */

.left {
	float:left;
	margin-right: 20px;
	margin-bottom: 10px;
	margin-top: 4px;
}

.right {
	float:right;
	margin-left: 20px;
	margin-bottom: 10px;
	margin-top: 4px;
}

.clearfix {
  clear: both;
}

.graybox {
    background-color: #f2f2f2;
	padding: 1px 16px 21px 16px;
	margin: 18px 0px 20px 0px;
	color:#262626;
	font-weight: 300;
}

.bluebox {
    background-color: #E4EDFA;
	padding: 1px 16px 21px 16px;
	margin: 18px 0px 20px 0px;
	color:#262626;
	font-weight: normal;
	border-left: 5px solid #003366;
}

.greenbox {
    background-color: #EBF0CC;
	padding: 1px 16px 21px 16px;
	margin: 18px 0px 20px 0px;
	color:#262626;
	font-weight: normal;
	border-left: 5px solid #A1B70D;
}
```
