### ISSUE TITLE
Potential skin problem: Resources > create folder > add details for this item > odd leading

### ISSUE THREAD

**Issue by hrvalli** [DukeLearningInnovation/duke-sakai-skins#86]
When I go to Resources, create a folder, and click on add details for this item, there's some odd leading going on for "Only members of this site can see this folder and its contents" and "Display this folder and its contents to selected groups only." See screenshot. 
<img width="536" alt="odd-text-display" src="https://user-images.githubusercontent.com/19862293/56387576-a1709280-61f2-11e9-8848-fb142067a419.png">

```CSS
.Mrphs-sakai-resources input[type="checkbox"] + label strong {
vertical-align: text-bottom;
}
```
while 
```CSS
.Mrphs-sakai-resources label {
vertical-align: top;
}
```
